### ISSUE TITLE
Do you have the paper list for Noisy Supervision Learning method on object detection?

### ISSUE THREAD

**Issue by sisrfeng** [subeeshvasu/Awesome-Learning-with-Label-Noise#13]
Hi, do you have the paper list for Noisy Supervision Learning method on object detection?
Most Noisy Supervision Learning method I found can only handel classifications task.

Many thanks

**Comment by subeeshvasu** [comment]
Hello, I haven't noticed any methods on object detection, but there could be some methods out there. If not, it can be an interesting research problem to pursue in near future. :)
