### ISSUE TITLE
Code for ICCV2019 "Symmetric Cross Entropy for Robust Learning with Noisy Labels" 

### ISSUE THREAD

**Issue by House-Leo** [subeeshvasu/Awesome-Learning-with-Label-Noise#2]
Code for ICCV2019 "Symmetric Cross Entropy for Robust Learning with Noisy Labels" https://github.com/YisenWang/symmetric_cross_entropy_for_noisy_labels

I think it can help you update!

**Comment by subeeshvasu** [comment]
Done.

Thank you.
