### ISSUE TITLE
Recommand our ICLR oral paper

### ISSUE THREAD

**Issue by hbzju** [subeeshvasu/Awesome-Learning-with-Label-Noise#43]
Hi,

Thanks for your wonderful collection of awesome papers with label-noise label learning! We would like to recommend our newly released paper [PiCO: Contrastive Label Disambiguation for Partial Label Learning](https://arxiv.org/abs/2201.08984), which has been accepted by ICLR 2022 as an oral presentation. Our work studied an important corrupted-label learning problem that mitigates the inherent label ambiguity in the annotation procedure. We believe our work is appropriate to be included in this repo!

Best.
Haobo

**Comment by subeeshvasu** [comment]
Done :)
