### ISSUE TITLE
Broken Paper Link

### ISSUE THREAD

**Issue by amilasilva92** [subeeshvasu/Awesome-Learning-with-Label-Noise#53]
Hi, 

Thank you for maintaining this wonderful repository. 
I have found that the paper link of the following paper on your repository has been broken. Could you please fix it with the correct link below.

Paper - Noise-Robust Learning from Multiple Unsupervised Sources of Inferred Labels
Link -  https://ojs.aaai.org/index.php/AAAI/article/view/20806/20565

Thank you.

**Comment by subeeshvasu** [comment]
Have updated, thank you for notifying me. Going forward feel free to raise a PR. :)
