### ISSUE TITLE
adding paper from cvpr 2022

### ISSUE THREAD

**Issue by xianglinyang** [subeeshvasu/Awesome-Learning-with-Label-Noise#54]
I think "Learning with Neighbor Consistency for Noisy Labels" from CVPR'22 is also relevant.

**Comment by JiarunLiu** [comment]
邮件已收到！

**Comment by subeeshvasu** [comment]
> I think "Learning with Neighbor Consistency for Noisy Labels" from CVPR'22 is also relevant.

Have added. Next time, if possible please raise a PR for the same.

Thanks.
