### ISSUE TITLE
adding related paper

### ISSUE THREAD

**Issue by mouxingyang** [subeeshvasu/Awesome-Learning-with-Label-Noise#55]
Thanks for the outstanding repository. I think "Learning with Twin Noisy Labels for Visible-Infrared Person Re-Identification" from CVPR'22 is also relevant.

**Comment by subeeshvasu** [comment]
> Thanks for the outstanding repository. I think "Learning with Twin Noisy Labels for Visible-Infrared Person Re-Identification" from CVPR'22 is also relevant.

Have added. Next time, if possible please raise a PR for the same.

Thanks.
