### ISSUE TITLE
add a paper from 2022 NeurIPS

### ISSUE THREAD

**Issue by wangren97** [subeeshvasu/Awesome-Learning-with-Label-Noise#56]
Thanks for your nice repository! 
I hope to share our recent work that investigates the study of learning from noise labels in the multi-view object classification case. 
The paper title is 'MVP-N: A Dataset and Benchmark for Real-World Multi-View Object Classification' [(link)](https://proceedings.neurips.cc/paper_files/paper/2022/file/819b8452be7d6af1351d4c4f9cbdbd9b-Paper-Datasets_and_Benchmarks.pdf) and accepted by NeurIPS 2022. 

Thanks

**Comment by JiarunLiu** [comment]
邮件已收到！

**Comment by subeeshvasu** [comment]
Done. Thank you. Feel free to raise a PR next time. :)
