### ISSUE TITLE
What are the simplest methods for the label noise problem?

### ISSUE THREAD

**Issue by guotong1988** [subeeshvasu/Awesome-Learning-with-Label-Noise#6]
If I have enough low quality data from unsupervised methods or rule-based methods.

In detail, I deal with a multi-label classification task. First I crawl web page such as wiki and use regex-based rule to mark the label. The model input is the wiki title and the model output is the rule-matched labels from wiki content. My task is to predict the labels for the wiki title.

Do you think **removing the wrong data predicted by trained model** is a simple but effective method?

@subeeshvasu  Thank you very much!

**Comment by subeeshvasu** [comment]
I did not understand what you meant by "wrong data predicted by trained model".

Some of the simple ideas that I have come across includes,
+ Iterative Cross Learning on Noisy Labels, Understanding and Utilizing Deep Neural Networks Trained with Noisy Labels - Partition the dataset int two halves, use two networks to train on each of them, and then based on the inference outputs from both networks fix the label errrors
+ mixup: BEYOND EMPIRICAL RISK MINIMIZATION - new data-augmentation scheme wherein a convex combination of random pairs of input data is fed to the network and the network is asked to predict the corresponding convex combination of labels
+ Making Deep Neural Networks Robust to Label Noise: a Loss Correction Approach - use transition probability matrix to account for errors

Checkout the survey papers, you might get a quick summarisation of the key ideas.
